### ISSUE TITLE
TypeError when adding the 

### ISSUE THREAD

**Issue by fubin1999** [LewisLabUCSD/GlyCompareCT#2]
I was using the GlyCompareCT executable, and got the error below:
```
Creating motif abundance table...
the glycan core is
Traceback (most recent call last):
  File "glyCompareCT.py", line 670, in <module>
  File "glyCompareCT.py", line 57, in main
  File "glyCompareCT.py", line 349, in structure
  File "glycompare/pipeline_functions.py", line 770, in select_motifs_pip
  File "glycompare/select_motifs.py", line 266, in __init__
TypeError: __init__() missing 1 required positional argument: 'num_processors'
[58627] Failed to execute script 'glyCompareCT' due to unhandled exception!
```

This error only appears when adding the "-d" argument. It happens for both glycompareCT.py and glycompareCT executable. 

More information for your reference:
- Device: MacBook Air M1, 2020
- System: MacOS Ventura 13.0.1
- Python version (for glycompareCT.py): 3.10.6

**Comment by zyj1729** [comment]
Thanks for reaching out. This seems to be an issue of the older glycompare version. You can try to download the latest glycompareCT release [v1.2.0](https://github.com/LewisLabUCSD/GlyCompareCT/releases/tag/v1.2.0) and test whether the executable works for drawing mode.

Or if you want to use the Python script, you can reinstall GlyCompareCT Github, remove the old glycompareCT virtual env by `conda env remove --name glycompareCT` and re-create the conda virtual env following the instruction. 

Please let me know if the issue persists. Also, we had not focused on providing flexibility for drawing glycomotif abundance results. That is one direction we intend to improve for GlyCompareCT. But currently the drawing mode is rather rigid as of figure types and layouts.

**Comment by fubin1999** [comment]
Thank you for your timely reply. I tried several times more and found that it is not about the "-d" argument. It turnt out I was using an old version downloaded several months ago. Anyway, I reinstall the latest glycompareCT and the problem seems gone.

Thanks again, and great work! 👍
